spring:
    cloud:
        config:
            enabled: true
            uri: http://configservice:8888
        stream:
            bindings:
                springCloudBusInput:
                    binder: rabbit
                springCloudBusOutput:
                    binder: rabbit
eureka:
    environment: prod
    region: hcm
    instance:
        prefer-ip-address: false
    client:
        enabled: false
        registerWithEureka: true
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://discoveryservice:8761/eureka
        registryFetchIntervalSeconds: 5
        healthcheck:
            enabled: true
management:
    endpoint:
        jolokia:
            enabled: true
    endpoints:
        shutdown:
            enabled: true
        security: false
        web:
            exposure:
                include: '*'
endpoints:
    sensitive: false