spring:
    cloud:
        config:
            server:
                retry:
                    initialInterval: 1000
                    multiplier: 1.1
                    maxInterval: 2000
                    maxAttempts: 6
                git:
                    uri: https://minhht@bitbucket.org/minhht/app-config.git
                    label: dev-local
                    skipSslValidation: false
                    searchPaths: '*'
                    ignoreLocalSshSettings: true
                    strictHostKeyChecking: false
                    clone-on-start: true
                    force-pull: true
                    basedir: ${user.home}/data/app-config
                    username: minhht
                    password: ENC(mS8LBiKFxdACFlrjdbdGLNmtRjVHlDX+)