spring:
    cloud:
        config:
            server:
                git:
                    uri: https://minhht@bitbucket.org/minhht/app-config.git
                    label: dev-local
                    skipSslValidation: false
                    searchPaths: '{application}'
                    ignoreLocalSshSettings: true
                    strictHostKeyChecking: false
                    clone-on-start: true
                    force-pull: true
                    basedir: ${user.home}/data/config-repo
                    username: minhht
                    password: ENC(mS8LBiKFxdACFlrjdbdGLNmtRjVHlDX+)
        bus:
            enabled: true
            trace:
                enabled: false
        stream:
            bindings:
                springCloudBus:
                    binder: rabbit
    rabbitmq:
        addresses: amqp://rabbitmq-dev:5672
        username: guest
        password: guest
eureka:
    environment: prod
    region: hcm
    instance:
        prefer-ip-address: false
    client:
        enabled: false
        registerWithEureka: true
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://discoveryservice:8761/eureka
        registryFetchIntervalSeconds: 5
        healthcheck:
            enabled: true
management:
    endpoint:
        jolokia:
            enabled: true
    endpoints:
        shutdown:
            enabled: true
        security: false
        web:
            exposure:
                include: '*'
endpoints:
    restart:
        enabled: true
    sensitive: false