spring:
    cloud:
        config:
            retry:
                initialInterval: 100000
                multiplier: 1.1
                maxInterval: 900000
                maxAttempts: 6
            server:
                bootrap: true
                git:
                    uri: https://git.spsvietnam.vn/Research_And_Development/config-repo.git
                    label: dev-local
                    search-paths: '*'
                    skipSslValidation: false
                    ignoreLocalSshSettings: true
                    strictHostKeyChecking: false
                    clone-on-start: true
                    force-pull: true
                    basedir: ${user.home}/data/config-repo
                    username: sw_test_gitlab
                    password: ENC(07b8RBlZEtbdwVMjUBnlyeFPWBIfoVBl)
        bus:
            enabled: false
            trace:
                enabled: false
        stream:
            bindings:
                springCloudBusInput:
                    binder: rabbit
                    group: ${spring.application.name}
                    destination: spring-cloud-bus
                springCloudBusOutput:
                    binder: rabbit
                    group: ${spring.application.name}
                    destination: spring-cloud-bus
    activemq:
        broker-url: tcp://activemq-dev:61616
        user: admin
        password: admin
eureka:
    environment: prod
    region: hcm
    instance:
        prefer-ip-address: false
    client:
        enabled: false
        registerWithEureka: true
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://discoveryservice:8761/eureka
        registryFetchIntervalSeconds: 5
        healthcheck:
            enabled: true
management:
    endpoint:
        jolokia:
            enabled: true
    endpoints:
        shutdown:
            enabled: true
        security: false
        web:
            exposure:
                include: '*'
endpoints:
    restart:
        enabled: true
    sensitive: false