server:
    port: 8080
spring:
    cloud:
        stream:
            bindings:
                springCloudBusInput:
                    binder: activemq
                springCloudBusOutput:
                    binder: activemq
        bus:
            enabled: true
            trace:
                enabled: false
    activemq:
        broker-url: tcp://activemq-dev:61616
        in-memory: false
        user: admin
        password: admin
    rabbitmq:
        addresses: amqp://rabbitmq-dev:5672
        username: guest
        password: guest
eureka:
    environment: prod
    region: hcm
    instance:
        prefer-ip-address: false
    client:
        enabled: false
        registerWithEureka: true
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://discoveryservice:8761/eureka
        registryFetchIntervalSeconds: 5
        healthcheck:
            enabled: true
management:
    endpoint:
        jolokia:
            enabled: true
    endpoints:
        shutdown:
            enabled: true
        security: false
        web:
            exposure:
                include: '*'
endpoints:
    restart:
        enabled: true
    sensitive: false