server:
    port: 8888
    ssl:
        key-alias: sps
        key-password: Spsvn@123
        key-store-password: Spsvn@123
        key-store: classpath:config/keystore.jks
        key-store-type: PKCS12
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://git.spsvietnam.vn/Research_And_Development/config-repo.git
                    searchPaths: '{application}'
                    ignoreLocalSshSettings: false
                    strictHostKeyChecking: false
                    host-key: Z2l0LnNwc3ZpZXRuYW0udm4=
                    hostKeyAlgorithm: ssh-rsa
                    clone-on-start: true
                    force-pull: true
                    basedir: ${user.home}/data/config-repo
                    privateKey: "-----BEGIN RSA PRIVATE KEY-----\nMIIEoQIBAAKCAQEA5r6/zcAWTXp0/a/y5oTq77AofhoSYDU1mzZT8IYkDj7NZkch\nts6uhcCEx+VrqEInRr2jqoJa8qRNTKvk1y5bzHpxlrgiCNycDd2TCVdZIeWrjp4K\nHrSmnARrVp5REltGgy88oDeMBTk8i72t1GAvNUjqEgeSCsY+Gj/CqCXAQLtHHqGY\nLiTGIQ0h2J0iGIzJaKh0Q33waNIQolIwidTw7KP4LCMPn++uWsFWIyhDwmVVFWms\nRIKavCfBHluCPTUSmq2bg43+UA13XRyWzjoypXaDAnt8LmjdEhooQEo3MXJNUrK3\nOVygUiJk279YnOB8m02w8yNg26DSH1+G/afdSwIBJQKCAQAStYUsW67IAwKRHBqd\nEbIvHB71d7xM/WU2GSlmh2q1DALQ8QK7y5GcJF3LBMOKLuCXCHUN0zfOfAZEfKPa\nGIP70pOWmU7eH7mgQmXeKa1H8Ab9ucl4HHw2Kd8wiWCE8qTaNEMvlc0VLieA87Ql\n+fX9Zsbe3gTsHelcEwHx9TkaATFgZ5EyjXXp7e3Vaqc1+vtN0W3tOxWJU/IS66Vn\nDzsU7w3/SuzPtDPdFYmUlfNz57SQRSD78jjsg5Z/pg9/w/hKTf1uPtmiOWl/M1gJ\nTUm8r7wdrnLgy4VmB6g6St/wTgp47nHA9SMWw9/OElKlVH8ixoxVNV8bw8HfGRWF\nOsvVAoGBAPajMXt9gBX1lPdTxQWJ0wFnsigF6SOnUTHzZE+UAHXpqgltLsaJrFQV\nGnBnfWz/hayHgm4dvh4RPImR7/ZOzHjJpusrRPnFxY1SnRzVjnoKkf+VMAnGpabw\n+u7bhvCFxZSwi+uSvO8ixg7Cf/7EZdCy+QPSGhK69PJNZ6QrX4z/AoGBAO+BHXNB\nKVc7rF/nX2OfoldBNKslEW3OdYpwPj5UGKJWIEIdAuBp6i/0R++THBwtYKBFPVID\nbmlF6aIQwMzGok48miVd7IhkLn+UW5GF8oCDwnNUjpQ99R42wMlAfSdtP4zOqfta\n0FXBQeMrsrPhaIvmGT+wzGPKPYi9F9lnHdO1AoGBAJKmORj+g4KtsoU4ulZR8xWX\nmlz8mHYQdXeleeogplPyuCFH1p+QIUbAcJXcq3E9/HRsP7cYmo5rHROHNLv3gH8r\nywhe6r4G5CqEJhElCJuXlRSCOD0qAaGIXdohqi4mBscc3ZL9Tb6fDfrwMG34PInt\n4CvJCJWD65b9l5IL85/xAoGAYRirEwyUOB8cXjs0glV5KkreADGfSDEa5Ri/SbNj\n7sj4Uidv3nAgq6g41r8ZO9sLfz6qKCrnknZJ9ZgWz47MLY4wp11tusDUlJYXSNVw\nJkNA/lK2V8YXQ5moGjy9HdJYCKbPSjmSuvtSD/z1a4TlMcv8Ze26pP72Wgd4Xw4g\n2UkCgYBZMKvilHqdnYJ1IUk0fwyZCacsP1HS6CbQbju+zNVD+Qz7zveIRIy7Px7m\nqMbkQ9+dG/B6+iPeW9hfM1ujDQf732dTTz+W9EPHbZ2i5pIszfOKuw49xIs+XkTI\nWkgKj9S1yY49R4veZQky6KM0tOi4g/hyUwCZMeV90D9wDMMS2g==\n-----END RSA PRIVATE KEY-----"
                    username: sw_test_gitlab
                    password: ENC(ef0NJ+qeyoQwiVHdrDhLfME2fJR0rMSH)
        bus:
            enabled: false
            trace:
                enabled: false
        stream:
            bindings:
                springCloudBusInput:
                    binder: rabbit
                springCloudBusOutput:
                    binder: rabbit
        rabbitmq:
            address: amqp://rabbitmq-dev:5672
            host: rabbitmq-host
            port: 5672
            username: guest
            password: guest
eureka:
    environment: prod
    region: hcm
    instance:
        prefer-ip-address: false
    client:
        enabled: false
        registerWithEureka: true
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://discoveryservice:8761/eureka
        registryFetchIntervalSeconds: 5
        healthcheck:
            enabled: true
management:
    endpoint:
        jolokia:
            enabled: true
    endpoints:
        shutdown:
            enabled: true
        security: false
        web:
            exposure:
                include: '*'
endpoints:
    sensitive: false