server:
    port: 8888
    ssl:
        enabled: false
        key-alias: sps
        key-password: Spsvn@123
        key-store-password: Spsvn@123
        key-store: classpath:config/keystore.jks
        key-store-type: PKCS12
        trust-store: classpath:config/keystore.jks
        trust-store-password: Spsvn@123
        trust-store-provider: EITHER
        trust-store-type: PKCS12
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://git.spsvietnam.vn/Research_And_Development/config-repo.git
                    skipSslValidation: true
                    searchPaths: '{application}'
                    ignoreLocalSshSettings: true
                    strictHostKeyChecking: false
                    host-key: Z2l0LnNwc3ZpZXRuYW0udm4=
                    hostKeyAlgorithm: ssh-rsa
                    clone-on-start: true
                    force-pull: true
                    basedir: ${user.home}/data/config-repo
                    privateKey: |-
                        -----BEGIN RSA PRIVATE KEY-----
                        MIIEoQIBAAKCAQEA5r6/zcAWTXp0/a/y5oTq77AofhoSYDU1mzZT8IYkDj7NZkch
                        ts6uhcCEx+VrqEInRr2jqoJa8qRNTKvk1y5bzHpxlrgiCNycDd2TCVdZIeWrjp4K
                        HrSmnARrVp5REltGgy88oDeMBTk8i72t1GAvNUjqEgeSCsY+Gj/CqCXAQLtHHqGY
                        LiTGIQ0h2J0iGIzJaKh0Q33waNIQolIwidTw7KP4LCMPn++uWsFWIyhDwmVVFWms
                        RIKavCfBHluCPTUSmq2bg43+UA13XRyWzjoypXaDAnt8LmjdEhooQEo3MXJNUrK3
                        OVygUiJk279YnOB8m02w8yNg26DSH1+G/afdSwIBJQKCAQAStYUsW67IAwKRHBqd
                        EbIvHB71d7xM/WU2GSlmh2q1DALQ8QK7y5GcJF3LBMOKLuCXCHUN0zfOfAZEfKPa
                        GIP70pOWmU7eH7mgQmXeKa1H8Ab9ucl4HHw2Kd8wiWCE8qTaNEMvlc0VLieA87Ql
                        +fX9Zsbe3gTsHelcEwHx9TkaATFgZ5EyjXXp7e3Vaqc1+vtN0W3tOxWJU/IS66Vn
                        DzsU7w3/SuzPtDPdFYmUlfNz57SQRSD78jjsg5Z/pg9/w/hKTf1uPtmiOWl/M1gJ
                        TUm8r7wdrnLgy4VmB6g6St/wTgp47nHA9SMWw9/OElKlVH8ixoxVNV8bw8HfGRWF
                        OsvVAoGBAPajMXt9gBX1lPdTxQWJ0wFnsigF6SOnUTHzZE+UAHXpqgltLsaJrFQV
                        GnBnfWz/hayHgm4dvh4RPImR7/ZOzHjJpusrRPnFxY1SnRzVjnoKkf+VMAnGpabw
                        +u7bhvCFxZSwi+uSvO8ixg7Cf/7EZdCy+QPSGhK69PJNZ6QrX4z/AoGBAO+BHXNB
                        KVc7rF/nX2OfoldBNKslEW3OdYpwPj5UGKJWIEIdAuBp6i/0R++THBwtYKBFPVID
                        bmlF6aIQwMzGok48miVd7IhkLn+UW5GF8oCDwnNUjpQ99R42wMlAfSdtP4zOqfta
                        0FXBQeMrsrPhaIvmGT+wzGPKPYi9F9lnHdO1AoGBAJKmORj+g4KtsoU4ulZR8xWX
                        mlz8mHYQdXeleeogplPyuCFH1p+QIUbAcJXcq3E9/HRsP7cYmo5rHROHNLv3gH8r
                        ywhe6r4G5CqEJhElCJuXlRSCOD0qAaGIXdohqi4mBscc3ZL9Tb6fDfrwMG34PInt
                        4CvJCJWD65b9l5IL85/xAoGAYRirEwyUOB8cXjs0glV5KkreADGfSDEa5Ri/SbNj
                        7sj4Uidv3nAgq6g41r8ZO9sLfz6qKCrnknZJ9ZgWz47MLY4wp11tusDUlJYXSNVw
                        JkNA/lK2V8YXQ5moGjy9HdJYCKbPSjmSuvtSD/z1a4TlMcv8Ze26pP72Wgd4Xw4g
                        2UkCgYBZMKvilHqdnYJ1IUk0fwyZCacsP1HS6CbQbju+zNVD+Qz7zveIRIy7Px7m
                        qMbkQ9+dG/B6+iPeW9hfM1ujDQf732dTTz+W9EPHbZ2i5pIszfOKuw49xIs+XkTI
                        WkgKj9S1yY49R4veZQky6KM0tOi4g/hyUwCZMeV90D9wDMMS2g==
                        -----END RSA PRIVATE KEY-----
                    username: sw_test_gitlab
                    password: ENC(07b8RBlZEtbdwVMjUBnlyeFPWBIfoVBl)
        bus:
            enabled: true
            trace:
                enabled: false
        stream:
            bindings:
                springCloudBus:
                    binder: rabbit
    rabbitmq:
        addresses: amqp://rabbitmq-dev:31274
        username: guest
        password: guest
eureka:
    environment: prod
    region: hcm
    instance:
        prefer-ip-address: false
    client:
        enabled: false
        registerWithEureka: true
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://discoveryservice:8761/eureka
        registryFetchIntervalSeconds: 5
        healthcheck:
            enabled: true
management:
    endpoint:
        jolokia:
            enabled: true
    endpoints:
        shutdown:
            enabled: true
        security: false
        web:
            exposure:
                include: '*'
endpoints:
    restart:
        enabled: true
    sensitive: false